[package]
name = "rocket-jwt-authorization"
version = "0.2.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/rocket-jwt-authorization"
homepage = "https://magiclen.org/rocket-jwt-authorization"
keywords = ["rocket", "server", "web", "authorization", "jwt"]
categories = ["parser-implementations", "web-programming"]
description = "This crate provides a procedural macro to create request guards used for authorization."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"

[dev-dependencies]
serde = "1"
serde_derive = "1"

rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }
rocket-include-tera = { git = "https://github.com/magiclen/rocket-include-tera", version = "0.5" }

once_cell = "1"

jwt = "0.13"
hmac = "0.10"
sha2 = "0.9"

validators = { git = "https://github.com/magiclen/validators", version = "0.23" }

[dev-dependencies.validators-derive]
version = "0.23"
git = "https://github.com/magiclen/validators"
default-features = false
features = ["rocket", "regex"]