[package]
name = "rocket-jwt-authorization-derive"
version = "0.3.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/magiclen/rocket-jwt-authorization"
homepage = "https://magiclen.org/rocket-jwt-authorization"
keywords = ["rocket", "server", "web", "authorization", "jwt"]
categories = ["parser-implementations", "web-programming"]
description = "This crate provides a procedural macro to create request guards used for authorization."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.3"
